# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/retail-analytics',
                'doc_host': 'https://charmi1128.github.io',
                'git_url': 'https://github.com/charmi1128/retail-analytics',
                'lib_path': 'retail_analytics'},
  'syms': {'retail_analytics.core': {'retail_analytics.core.foo': ('core.html#foo', 'retail_analytics/core.py')}}}
