project:
  type: website

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    page-layout: article
    toc: true
    code-fold: true
    code-tools: true

website:
  title: 'Data Analytics'
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]
